title: "Quantum Threat"
email: self@jackalyst.com
description: >- # this means to ignore newlines until "baseurl:"
  Testing
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jackalyst
github_username:  jackalyst
defaults:
  - scope: 
      path: ""
    values:
      layout: "default"
# Build settings
markdown: kramdown
exclude: ['assets/raw/']
kramdown:
  extensions: [footnotes] 
local_theme: qccalc